# Generated by Django 2.2.13 on 2020-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201219_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_imgs'),
        ),
    ]
