# Generated by Django 2.2.13 on 2021-01-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210110_1647'),
        ('users', '0012_auto_20210111_1307'),
    ]

    operations = [
    ]
