# Generated by Django 2.2.13 on 2021-02-18 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0006_remove_place_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('room_type', models.CharField(choices=[('ROOM_SINGLE', 'Single'), ('ROOM_DOUBLE', 'Double'), ('ROOM_TWIN', 'Twin'), ('ROOM_TRIPLE', 'Triple'), ('ROOM_SUITE', 'Suite')], max_length=30)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='places.Place')),
            ],
        ),
    ]
