# Generated by Django 3.1.4 on 2021-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(choices=[('ROOM_SINGLE', 'Single'), ('ROOM_DOUBLE', 'Double'), ('ROOM_TWIN', 'Twin'), ('ROOM_TRIPLE', 'Triple'), ('ROOM_SUITE', 'Suite')], max_length=30),
        ),
    ]
