# Generated by Django 2.2.13 on 2020-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20201216_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='contentid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_img',
            field=models.ImageField(blank=True, upload_to='place_imgs'),
        ),
    ]
