# Generated by Django 2.2.13 on 2020-12-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20201220_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
