# Generated by Django 2.2.13 on 2020-12-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20201229_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='writer',
        ),
    ]
